name: Test

on:
  pull_request_target:
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.20.x, 1.21.x ]

    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: go test -short -v -race ./...
